import type { Metadata } from "next";
import "./globals.css";
import App from "./App";


export const metadata: Metadata = {
    title: "Create Next App", description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (<html lang="en">
        <head>
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin={"anonymous"} />
            <link
                href="https://fonts.googleapis.com/css2?family=Dosis:wght@200..800&family=Oxygen:wght@300;400;700&display=swap"
                rel="stylesheet" />
        </head>
        <body>
            <App>
                {children}
            </App>
        </body>
    </html>);
}
